# Renommer ce fichier par constantes.yaml et remplir le mot de passe de la base de données

# Connexion à la base de donnée
DB_:
  HOST: # Adresse de la BD
  NAME: # Le nom de la BD
  USER: # Le nom de l'utilisateur pour la BD
  PASS:  # Son mot de passe
PREFIXE_TABLE: vhs_

# Constante de la partie vue (à ne pas modifier)
WEBSITE_:
  TITLE: VHS - Video Home Share
  VERSION: 1.0
  DESCRIPTION: Un site de partage de films
  LANGUAGE: fr
  LOGO: img\LogoPopCorn.png

# API TMDB (a ne pas modifier)
TMDB_:
  CLE_KEY: # Clé d'API TMDB
  TOKEN_ACCES: # Token d'accès TMDB
