# Renommer par template.yaml et remplir me mdp

# Connexion à la base de donnée
DB_:
  HOST: lakartxela.iutbayonne.univ-pau.fr
  NAME: namrein_pro
  USER: namrein_pro
  PASS: # A compléter
PREFIXE_TABLE: vhs_

# Constante de la partie vue
WEBSITE_:
  TITLE: VHS - Video Home Share
  VERSION: 1.0
  DESCRIPTION: Un site de partage de films
  LANGUAGE: fr