# Renommer ce fichier par constantes.yaml et remplir le mot de passe de la base de données

# Connexion à la base de donnée
DB_:
  HOST: localhost
  NAME: vhs
  USER: root
  PASS:  
PREFIXE_TABLE: vhs_

# Constante de la partie vue
WEBSITE_:
  TITLE: VHS - Video Home Share
  VERSION: 1.0
  DESCRIPTION: Un site de partage de films
  LANGUAGE: fr
  LOGO: img\LogoPopCorn.png
